---
title: "Project"
author: "Prakhar Mishra"
date: "November 25, 2019"
output: html_document
---

```{r}
library(ggplot2)
library(gridExtra)
library(survival)
library(dplyr)
```


```{r}
bitcoin_data <- read.csv("bitstampUSD_1-min_data_2012-01-01_to_2017-05-31.csv")

#Using only complete cases

bitcoins <- bitcoin_data[complete.cases(bitcoin_data), ]
```

```{r}
#Converting UNIX time

bitcoins$Time.read <- as.POSIXct(bitcoins$Timestamp, origin = "1970-01-01", tz = "GMT")
bitcoins$Year <- format(as.Date(bitcoins$Time.read, format="%d/%m/%Y"),"%Y")
bitcoins$Month <- format(as.Date(bitcoins$Time.read, format="%d/%m/%Y"),"%m")
bitcoins$YearMonth <- format(as.Date(bitcoins$Time.read, format="%d/%m/%Y"),"%Y-%m")
bitcoins$Day <- format(as.Date(bitcoins$Time.read, format="%d/%m/%Y/%H/%M/%S"),"%d")
bitcoins$Time <- format(as.POSIXct(bitcoins$Time.read), format = "%H:%M:%S")
bitcoins$Intervals <- format(as.POSIXct(bitcoins$Time.read), format = "%H")
bitcoins$Min.Sec <- format(as.POSIXct(bitcoins$Time.read), format = "%M:%S")


```


```{r}
bitcoins$Transact <- ifelse(bitcoins$Volume..BTC. >=0, 1, 0)
bitcoins$Transact[is.na(bitcoins$Transact)] <- 0

# = = = When data is rearranged to look into the number of transactions per variable = = =

Trns.bit <- (aggregate(cbind(Transact, Volume..BTC., Volume..Currency.) ~ Intervals + Day + Month + YearMonth + Year, data = bitcoins, sum))
tTrnsbit <- subset(Trns.bit, Year == 2013 | Year == 2014 | Year == 2015)
tTrnsbit$Year <- as.factor(tTrnsbit$Year)
Trns.bit$Year <- as.factor(Trns.bit$Year)
Trns.bit$YearMonth <- as.factor(Trns.bit$YearMonth)
Trns.bit$Month <- as.factor(Trns.bit$Month)
Trns.bit$Day <- as.factor(Trns.bit$Day)
Trns.bit$Intervals <- as.factor(Trns.bit$Intervals)
str(Trns.bit)


# = = = The next levels as per Transactions = = =

summary(tTrnsbit$Transact)
Trns.bitQ1 <- subset(tTrnsbit, Transact <= 33)
Trns.bitQ2 <- subset(tTrnsbit, Transact > 33 & Transact <= 45)
Trns.bitQ3 <- subset(tTrnsbit, Transact > 45 & Transact <= 54)
Trns.bitQ4 <- subset(tTrnsbit, Transact > 54)


# = = = = Quadrants of Transactions/Day/Hour = = = =

summary(tTrnsbit$Transact)

# = = = Transactions' Quadrants based graphs Volumes in BTC = = = = 

pBTCQ1 <- ggplot(Trns.bitQ1, aes(x=Transact, y=Month)) +
  geom_point(aes(size = Volume..BTC.), col = "red", alpha = 0.27)+
  facet_grid(.~Year, scales = "free")+
  xlab("1st Quar - Transactions/Day/Hour")+
  ylab("Months")+
  theme(legend.position = "top")
pBTCQ2 <- ggplot(Trns.bitQ2, aes(x=Transact, y=Month)) +
  geom_point(aes(size = Volume..BTC.), col = "darkgreen", alpha = 0.27)+
  facet_grid(.~Year, scales = "free")+
  xlab("2nd Quar - Transactions/Day/Hour")+
  ylab("Months")+
  theme(legend.position = "top")
pBTCQ3 <- ggplot(Trns.bitQ3, aes(x=Transact, y=Month)) +
  geom_point(aes(size = Volume..BTC.), col = "maroon", alpha = 0.27)+
  facet_grid(.~Year, scales = "free")+
  xlab("3rd Quar - Transactions/Day/Hour")+
  ylab("Months")+
  theme(legend.position = "top")
pBTCQ4 <- ggplot(Trns.bitQ4, aes(x=Transact, y=Month)) +
  geom_point(aes(size = Volume..BTC.), col = "royalblue", alpha = 0.27)+
  facet_grid(.~Year, scales = "free")+
  xlab("4th Quar - Transactions/Day/Hour")+
  ylab("Months")+
  theme(legend.position = "top")
Trns.Qua.BTC <- grid.arrange(pBTCQ1, pBTCQ2, pBTCQ3, pBTCQ4)
Trns.Qua.BTC
```


```{r}
bitcoins$Model_price[bitcoins$Year=='2011'] <- '32'
bitcoins$Model_price[bitcoins$Year=='2012'] <- '65'

bitcoins$Model_price[bitcoins$YearMonth == '2013-01']<-'68.00'
bitcoins$Model_price[bitcoins$YearMonth == '2013-02']<-'68.00'
bitcoins$Model_price[bitcoins$YearMonth == '2013-03']<-'68.00'
bitcoins$Model_price[bitcoins$YearMonth == '2013-04']<-'68.00'
bitcoins$Model_price[bitcoins$YearMonth == '2013-05']<-'68.00'
bitcoins$Model_price[bitcoins$YearMonth == '2013-06']<-'68.73'
bitcoins$Model_price[bitcoins$YearMonth == '2013-07']<-'79.83'
bitcoins$Model_price[bitcoins$YearMonth == '2013-08']<-'96.36'
bitcoins$Model_price[bitcoins$YearMonth == '2013-09']<-'126.01'
bitcoins$Model_price[bitcoins$YearMonth == '2013-10']<-'199.575'
bitcoins$Model_price[bitcoins$YearMonth == '2013-11']<-'296.25'
bitcoins$Model_price[bitcoins$YearMonth == '2013-12']<-'684.72'
bitcoins$Model_price[bitcoins$YearMonth == '2014-01']<-'848.03'
bitcoins$Model_price[bitcoins$YearMonth == '2014-02']<-'626.196'
bitcoins$Model_price[bitcoins$YearMonth == '2014-03']<-'584.2'
bitcoins$Model_price[bitcoins$YearMonth == '2014-04']<-'435.926'
bitcoins$Model_price[bitcoins$YearMonth == '2014-05']<-'559.79'
bitcoins$Model_price[bitcoins$YearMonth == '2014-06']<-'621.0533'
bitcoins$Model_price[bitcoins$YearMonth == '2014-07']<-'599.135'
bitcoins$Model_price[bitcoins$YearMonth == '2014-08']<-'515.163'
bitcoins$Model_price[bitcoins$YearMonth == '2014-09']<-'411.59'
bitcoins$Model_price[bitcoins$YearMonth == '2014-10']<-'371.19'
bitcoins$Model_price[bitcoins$YearMonth == '2014-11']<-'386.085'
bitcoins$Model_price[bitcoins$YearMonth == '2014-12']<-'330.796'
bitcoins$Model_price[bitcoins$YearMonth == '2015-01']<-'254.65'
bitcoins$Model_price[bitcoins$YearMonth == '2015-02']<-'249.525'
bitcoins$Model_price[bitcoins$YearMonth == '2015-03']<-'257.775'
bitcoins$Model_price[bitcoins$YearMonth == '2015-04']<-'250.11'
bitcoins$Model_price[bitcoins$YearMonth == '2015-05']<-'248.41'
bitcoins$Model_price[bitcoins$YearMonth == '2015-06']<-'255.365'
bitcoins$Model_price[bitcoins$YearMonth == '2015-07']<-'266.345'
bitcoins$Model_price[bitcoins$YearMonth == '2015-08']<-'240.92'
bitcoins$Model_price[bitcoins$YearMonth == '2015-09']<-'243.495'
bitcoins$Model_price[bitcoins$YearMonth == '2015-10']<-'256.77'
bitcoins$Model_price[bitcoins$YearMonth == '2015-11']<-'290.14'
bitcoins$Model_price[bitcoins$YearMonth == '2015-12']<-'385.8633'
bitcoins$Model_price[bitcoins$YearMonth == '2016-01']<-'412.41'
bitcoins$Model_price[bitcoins$YearMonth == '2016-02']<-'396.65'
bitcoins$Model_price[bitcoins$YearMonth == '2016-03']<-'417.27'
bitcoins$Model_price[bitcoins$YearMonth == '2016-04']<-'440.273'
bitcoins$Model_price[bitcoins$YearMonth == '2016-05']<-'443.72'
bitcoins$Model_price[bitcoins$YearMonth == '2016-06']<-'674.7'
bitcoins$Model_price[bitcoins$YearMonth == '2016-07']<-'687.56'
bitcoins$Model_price[bitcoins$YearMonth == '2016-08']<-'687.22'
bitcoins$Model_price[bitcoins$YearMonth == '2016-09']<-'752.255'
bitcoins$Model_price[bitcoins$YearMonth == '2016-10']<-'824.86'
bitcoins$Model_price[bitcoins$YearMonth == '2016-11']<-'863.965'
bitcoins$Model_price[bitcoins$YearMonth == '2016-12']<-'982.056'
bitcoins$Model_price[bitcoins$YearMonth == '2017-01']<-'1175.525'
bitcoins$Model_price[bitcoins$YearMonth == '2017-02']<-'1389.88'
bitcoins$Model_price[bitcoins$YearMonth == '2017-03']<-'1542.01'
bitcoins$Model_price[bitcoins$YearMonth == '2017-04']<-'1679.52'
bitcoins$Model_price[bitcoins$YearMonth == '2017-05']<-'1681.695'
bitcoins$Model_price[bitcoins$YearMonth == '2017-06']<-'2239.49'
bitcoins$Model_price[bitcoins$YearMonth == '2017-07']<-'2548.427'
bitcoins$Model_price[bitcoins$YearMonth == '2017-08']<-'2917.47'
bitcoins$Model_price[bitcoins$YearMonth == '2017-09']<-'3263.3'
bitcoins$Model_price[bitcoins$YearMonth == '2017-10']<-'4051.67'
bitcoins$Model_price[bitcoins$YearMonth == '2017-11']<-'4367.055'
bitcoins$Model_price[bitcoins$YearMonth == '2017-12']<-'5579.17'


```



```{r}
#Number of cryptocurrency competitors that bitocoin had by year
bitcoins$Competition[bitcoins$Year == "2011"] <- "4"
bitcoins$Competition[bitcoins$Year == "2012"] <- "6"
bitcoins$Competition[bitcoins$Year == "2013"] <- "66"
bitcoins$Competition[bitcoins$Year == "2014"] <- "506"
bitcoins$Competition[bitcoins$Year == "2015"] <- "562"
bitcoins$Competition[bitcoins$Year == "2016"] <- "644"
bitcoins$Competition[bitcoins$Year == "2017"] <- "1335"

```


```{r}
#Calculating the ratio of the market price and the weighted price
bitcoins$PriceRatio <- as.numeric(bitcoins$Weighted.Price)/as.numeric(bitcoins$Model_price)

#Add a column that puts in the status for the hazard
bitcoins$Status <- ifelse(bitcoins$PriceRatio >= 1, 1, 0)

```


```{r}
#Survival Analysis

model= Surv(as.numeric(bitcoins$Year), as.numeric(bitcoins$Open))
survfit(model , data=bitcoins) %>% plot(mark.time=T, xlab="Years", ylab="p(survive)")
survfit(model , data=bitcoins) %>% summary()



# real data
ldat = bitcoins %>% tbl_df()
ldat
km = Surv(as.numeric(ldat$time), as.numeric(ldat$Competition)) %>%
  (function(x) survfit(x ~ 1, data=ldat))(.)
# Kaplan-Meier curve
plot(km, xlab= D)
class(ldat$status)

```


```{r}
library(Matrix)
library(xgboost)
#Splitting into train and test set

## 75% of the sample size
smp_size <- floor(0.75 * nrow(bitcoins))

## set the seed to make partition reproducible
set.seed(123)
train_ind <- sample(seq_len(nrow(bitcoins)), size = smp_size)

train <- bitcoins[train_ind, ]
test <- bitcoins[-train_ind, ]

label <- train$Weighted.Price

#Returns object unchanged if there are NA values
previous_na_action<- options('na.action')
options(na.action='na.pass')

#Build matrix input for the model
trainMatrix <- sparse.model.matrix(Weighted.Price ~ Volume..BTC. + Volume..Currency.
                                   + YearMonth +Model_price +Competition 
                                   , data = train
                                   #, contrasts.arg = c('Competition')
                                   , sparse = FALSE, sci = FALSE)

options(na.action = previous_na_action$na.action)

#Creating input for xgboost
trainDMatrix <- xgb.DMatrix(data = trainMatrix, label = label)

#Setting parameters of model
params <- list(booster = "gbtree"
               , objective = "reg:linear"
               , eta=0.4
               , gamma=0
               )

#Cross-validation
xgb.tab <- xgb.cv(data = trainDMatrix
                  , param = params
                  , maximize = FALSE, evaluation = "rmse", nrounds = 100
                  , nthreads = 10, nfold = 2, early_stopping_round = 10)
```

```{r}
library(data.table)
library(dplyr)
library(padr)
library(xgboost)
library(Matrix)
library(RcppRoll)
library(zoo)
library(Ckmeans.1d.dp)

#Building the model to predict the weighted price

#Number of rounds
num_iterations = xgb.tab$best_iteration

model <- xgb.train(data = trainDMatrix
                               , param = params
                               , maximize = FALSE, evaluation = 'rmse' 
                               , nrounds= num_iterations)

importance <- xgb.importance(feature_names = colnames(trainMatrix), model = model)
importance_2 <- importance[1:10,]
xgb.ggplot.importance(importance_matrix = importance_2)

```


```{r}

#Returns object unchanged if there are NA values
previous_na_action<- options('na.action')
options(na.action='na.pass')

#Build matrix input for the model
testMatrix <- sparse.model.matrix(Weighted.Price~ Volume..BTC. + Volume..Currency.
                                   + YearMonth +Model_price +Competition 
                                   , data = test
                                   #, contrasts.arg = c('Competition')
                                   , sparse = FALSE, sci = FALSE)

options(na.action = previous_na_action$na.action)

#Predict values for a given day
pred <- predict(model, testMatrix)

```


```{r}

```

